// ExcelAddin.idl : ExcelAddin 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(ExcelAddin.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(8B62679E-4CF7-4B98-9366-FE03F337FB27),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ISimpleAddin : IDispatch{
};
[
	uuid(ED9F0E3B-520F-47B4-911B-350CC2873EB0),
	version(1.0),
]
library ExcelAddinLib
{
	importlib("stdole2.tlb");
	[
		uuid(96A39598-853F-4CF6-A23E-8D31B0CED3C4)		
	]
	coclass SimpleAddin
	{
		[default] interface ISimpleAddin;
	};
};

